### ISSUE TITLE
in طلب توظيف page - pressing ارسال  more than one time - duplicate it in cp

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#10]
1- from website 
2-  from side menu click on الخدمات الالكترونية  
3- then طلب التوظيف
4- enter data
5- click on  ارسال more than one time 
6- check fron cp

expected
find it one request
actual
duplicated it in cp

![image](https://user-images.githubusercontent.com/94896038/184177909-1a0af8dd-bd54-4b46-92c9-c89383cd04ea.png)

**Comment by nesmamarassy** [comment]
نفس حاله التاريخ
