### ISSUE TITLE
all internal pages - make page title appears lonly not the flow 

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#14]
1- open the web site
2-from side menu click on السايسات

expected
find السياسات
actual
find الرئيسية - الحوكمة - السياسات
![image](https://user-images.githubusercontent.com/94896038/184179111-1cda2b6b-1f41-48e3-a476-206a890d14ec.png)

**Comment by nesmamarassy** [comment]
this is site map 
not an issue
