### ISSUE TITLE
openning and closing main item redirect to its page

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#16]
1- open website
2- click on side menu
3- click on عن الجمعية - طلبات المشاركة في الدعم arrow (parent) to show its items (childs)

expected
open items below it without any redirection
actual
redirect to عن الجمعية - طلبات المشاركة في الدعم page

**Comment by nesmamarassy** [comment]
ده طلب العميل لان عن الجمعيه مقاله اصلا

**Comment by Remotework21** [comment]
hy- closed
