### ISSUE TITLE
lot of defined pages name are not highlighted

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#17]
1- open website
2- click on side menu
3- click on التطوع - الكوادر العاملة بالقطاع

expected
 الكوادر العاملة بالقطاع  is highlighted from side menu
actual
التطوع  (main item) is highlighted
![image](https://user-images.githubusercontent.com/94896038/184180311-347e8b8b-b71b-4a78-9072-3ff9b2a4decd.png)

![image](https://user-images.githubusercontent.com/94896038/184180356-b6a540b9-c051-4089-b227-dcdb8fe25a8c.png)

**Comment by nesmamarassy** [comment]
لان الفرص التطوعيه منيو فرعيه من التطوع
sup menu
