### ISSUE TITLE
طلب في صفحة استمارة طلب وظيفة

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#19]
في صفحة استمارة طلب وظيفة مطلوب إخفاء الاستمارة في الوقت الحالي وإضافة جملة "لا توجد وظائف في الوقت الحالي"
الرابط
https://www.jkmm.org.sa/ElectronicServices/JobApplication

**Comment by mohamedkhatab079** [comment]
ready to test
