### ISSUE TITLE
add   خبر  from cp appears with details section only in news page 

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#2]
"1- open cp 
2- clicl on  الاخبار
3- اضافة 
4- enter data and save 
5- click on المزيد من التفاصيل  from  news bar
6- check news page

expected
find news appear with titles and when i click on title go to details page 
actual
appears with details section only in news page
![image](https://user-images.githubusercontent.com/94896038/184165350-f36f56ef-2719-49e1-b443-9eed6f7d7af9.png)
![image](https://user-images.githubusercontent.com/94896038/184165531-8b6cb0cd-af4b-47e1-9bf9-7b5561723843.png)

**Comment by nesmamarassy** [comment]
done

**Comment by Remotework21** [comment]
reopen 
![image](https://user-images.githubusercontent.com/94896038/186411725-b1d704a0-598c-4474-a43d-d4b3ab21baa6.png)
![image](https://user-images.githubusercontent.com/94896038/186411822-8bccebeb-f686-4b73-bda7-089d29a38820.png)
