### ISSUE TITLE
عن الجمعية - cut photo (design bug)

### ISSUE THREAD

**Issue by Mariamboshra31** [Remotework21/Makkah-project#25]
1- open website link https://www.jkmm.org.sa/Home from mobile browser
2- click on عن الجمعية 
3- scroll and check data

expected : photo should not be cut and user can see it well should be in the center 
actual : the photo is cut 
![cut photo](https://user-images.githubusercontent.com/108907189/198303365-83c2e324-1c3c-42ab-8a0b-b8991654c310.jpeg)

**Comment by alaa-said** [comment]
not found
