### ISSUE TITLE
طلب إضافة صفحة اللجان التخصصية 

### ISSUE THREAD

**Issue by Remotework21** [Remotework21/Makkah-project#33]
مطلوب إضافة صفحة اللجان التخصصية تحت فئة الحوكمة داخل الكنترول بانل

**Comment by mohamedkhatab079** [comment]
@Remotework21 
اللجان التخصصية عبارة عن تاب تحتها اكتر من صفحة و مش فى الكنترول بانل هى موجودة فى السايت, ممكن تفاصيل اكتر و اضافة الروابط
