### ISSUE TITLE
member name inside the title textbox  (not all member name appears ) (design bug) - mobile app 

### ISSUE THREAD

**Issue by Mariamboshra31** [Remotework21/Makkah-project#46]
صفحة سعادة الدكتور عيسى بن محمد رواس/ صفحة سعادة الاستاذ محمد بن امين عطاس/صفحة سعادة الاستاذ محمد بن فؤاد ابو الخير/ 
 صفحة سعادة الاستاذ وليد بن محمد سمباوة

1- open website link https://www.jkmm.org.sa/Home from mobile browser
2- choose  عن الجمعية
3- click on الهيكل الادارى 
4- choose (ex.سعادة الدكتور عيسى بن محمد رواس)

expected result : whole name appears 
actual result : not all member name appears 

screenshot : 
![Screenshot_213](https://user-images.githubusercontent.com/108907189/204736328-1df71816-8a77-45a2-9ba2-334d21aedf14.png)
![Screenshot_224](https://user-images.githubusercontent.com/108907189/204995348-2293bd95-dc87-434c-a3dc-d52aded75af3.png)
![Screenshot_225](https://user-images.githubusercontent.com/108907189/204995354-f9304e58-0be6-48dc-bf3b-4fb4382fcbb2.png)
![Screenshot_226](https://user-images.githubusercontent.com/108907189/204995355-f0cddb8a-a13a-4544-b699-aa744384d2ab.png)

**Comment by Mariamboshra31** [comment]
closed

**Comment by alaa-said** [comment]
done
