### ISSUE TITLE
there is no space between فى الصفحات  (design bug) - mobile issue 

### ISSUE THREAD

**Issue by Mariamboshra31** [Remotework21/Makkah-project#52]
صفحة الخدمات الالكترونية/ صفحة الحوكمة / صفحة  الهيكل الدارى 
1- open website link https://www.jkmm.org.sa/Home from mobile browser
2- click on الخدمات الالكترونية 

expected result : spaces between الصفحات الفرعية
actual result: no spaces between الصفحات الفرعية 

screenshot :
![Screenshot_221](https://user-images.githubusercontent.com/108907189/204835372-9612b6ae-65fd-43e8-af36-4b8ca14831ed.png)
![Screenshot_222](https://user-images.githubusercontent.com/108907189/204835377-fc90398f-9cbd-44c4-b9f3-611c8641b2de.png)
![Screenshot_223](https://user-images.githubusercontent.com/108907189/204835393-c9ece082-c8f7-4924-9943-dc337ffa137c.png)

**Comment by Mariamboshra31** [comment]
closed

**Comment by alaa-said** [comment]
done
