### ISSUE TITLE
footer needs to be edited -mobile issue (design bug)

### ISSUE THREAD

**Issue by Mariamboshra31** [Remotework21/Makkah-project#56]
1- open website link https://www.jkmm.org.sa/Home from mobile browser
2- click on عن الجمعية 

expected result : footer should be crosswise
actual result : footer is lengthwise

screenshot: 
![Screenshot_232](https://user-images.githubusercontent.com/108907189/205063761-ac48dbeb-5c4b-4ec6-85e7-d7dcaa8cdbb7.png)

**Comment by alaa-said** [comment]
done
