### ISSUE TITLE
when scrolling the menu doesn't appear the last two content (two choice)مشاريع الجمعية / الانجازات(design bug) -mobile app 

### ISSUE THREAD

**Issue by Mariamboshra31** [Remotework21/Makkah-project#57]
1- open website link https://www.jkmm.org.sa/Home from mobile browser
2- click on عن الجمعية
3- open the menu and scroll it down to show the last content 

expected result : appear all menu 
actual result : the last two choices don't appear مشاريع الجمعية / الانجازات 

screenshot :  

https://user-images.githubusercontent.com/108907189/205479385-1f9d548d-07f6-4afe-85d3-da13e9183c54.mp4

**Comment by Mariamboshra31** [comment]
reopen .. still existed if user open any drop down list from the menu those two choices doesn't appear

**Comment by alaa-said** [comment]
not found

**Comment by Mariamboshra31** [comment]
Closed
